name: Rockwall
version: '${version}'
main: me.cobble.rockwall.rockwall.Rockwall
api-version: 1.19
softdepend: [ PlaceholderAPI ]
authors: [ Cbble_ ]
description: An advanced, highly-configurable and powerful chat system
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0'
permissions:
  rockwall.color:
    description: Allows players to send colored messages
    default: op
  rockwall.massmention:
    description: Allows the player to use @here or @everyone
    default: op
  rockwall.clearchat:
    default: op
    description: Allows players to clear chat
  rockwall.admin:
    default: op
    description: Allows access to admin commands
    children:
      - rockwall.admin.join
  rockwall.admin.join:
    description: Allows access to joining admin parties
    default: op
  rockwall.admin.create:
    default: op
    description: Allows for creating admin parties
commands:
  rockwall:
    aliases:
      - rock
      - rwall
      - rw
    description: Admin command for Rockwall

